using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    private float speed = 20.0f;
    
    private float turnSpeed = 50.0f;

    private float hInput;

    private float fInput;

    // Update is called once per frame
    void Update()
    {
       hInput = Input.GetAxis("Horizontal");
       fInput = Input.GetAxis("Vertical");

      // Makes the player move
      transform.Translate(Vector3.forward * Time.deltaTime * speed * fInput);  
      // Rotating character 
      transform.Rotate(Vector3.up, turnSpeed * Time.deltaTime * hInput);
    }
}
